### ISSUE TITLE
convert inline geojson to vectorcube in aggregate_spatial

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-driver#141]

**Comment by soxofaan** [comment]
done by aee2c00

**Comment by soxofaan** [comment]
reopening to follow up failing integration tests as result of this change:

- test_random_forest_train_and_load_from_jobid
```
        # Check job_metadata.json.
        with open(metadataPath, "r") as f:
            metadata = json.load(f)
>           assert metadata["geometry"].get("type", "") == "GeometryCollection"
E           AssertionError: assert 'Polygon' == 'GeometryCollection'
E             - GeometryCollection
E             + Polygon
openeo-geopyspark-integrationtests/tests/test_integration.py:601: AssertionError
```

- test_integration.test_point_timeseries
    > E       openeo.rest.OpenEoApiError: [500] Internal: Server error: class org.locationtech.jts.geom.Point cannot be cast to class org.locationtech.jts.geom.Polygon (org.locationtech.jts.geom.Point and org.locationtech.jts.geom.Polygon are in unnamed module of loader org.apache.spark.util.MutableURLClassLoader @66629f63) (ref: r-60568a1627d94a23b7ed88fa11e07cc4)


- test_integration.test_point_timeseries_from_batch_process
    > E       openeo.rest.OpenEoApiError: [500] Internal: Server error: AttributeError("'DriverVectorCube' object has no attribute 'is_empty'") (ref: r-436f0bac03f741739a56a509fea6f87e)

**Comment by soxofaan** [comment]
- `test_random_forest_train_and_load_from_jobid`  is fixed now
- `test_point_timeseries_from_batch_process`  passes again now 
- `test_point_timeseries` is still failing despite https://github.com/Open-EO/openeo-python-driver/commit/2ec255ea172b267ac0d632bbbdacde293585079e

**Comment by soxofaan** [comment]
Failing integration tests due to #141 changes are now fixed.
Part of it was a quick fix to roll back old behavior for point geometries (2ec255ea172b267ac0d632bbbdacde293585079e, 4927eee0df440a808145592f3c6e4405d3121f3e).
Next up is properly handling point geometries in vector cube code paths

**Comment by soxofaan** [comment]
problem with point geometries is addressed now as well (Open-EO/openeo-geopyspark-driver#239)
time to close this one again
